services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
  web:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
  
  celery:
    build: .
    command: celery -A app worker --loglevel=INFO --concurrency 1 -P solo
    restart: always
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
  
  celery-beat:
    build: .
    command: celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: always
    volumes:
      - .:/app
    depends_on:
      - rabbitmq